pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/Pratiklanjewar2025/project_autoscaling.git'
            }
        }
        stage('Deploy with Terraform') {
            steps {
                sh 'terraform init'
                sh 'terraform apply -auto-approve'
            }
        }
        stage('Start Docker Containers') {
            steps {
                sh 'docker-compose up -d'
            }
        }
    }
}
