pipeline {
    agent any
    stages {
        stage('Clone Repository') {
            steps {
                git 'https://github.com/your-repo/project_autoscaling.git'
            }
        }
        stage('Deploy Server') {
            steps {
                sh 'bash scripts/trigger_autoscaling.sh'
            }
        }
        stage('Cleanup Unused Servers') {
            steps {
                sh 'bash scripts/delete_unused_servers.sh'
            }
        }
    }
}
